### ISSUE TITLE
Treasure Chests can be shot

### ISSUE THREAD

**Issue by appgurueu** [rubenwardy/ctf_pvp_engine#23]
Title says it all. Played on rubenwardy's CTF Server. Tried shooting at a Treasure Chest with Rifle/Shotgun and it burst/disappeared, without dropping the items.

**Comment by ClobberXD** [comment]
Wrong repo. This should go to https://github.com/rubenwardy.com/capturetheflag since that subgame adds the treasure chests mod(s).
